---
title: "Country DQ Groupings"
author: "Lillian Chen"
date: "1/22/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(easypackages)
library(data.table)

#packages needed for spatial data analysis in R
pkgs<- c("devtools","animation","dismo",
         "gdalUtils","geosphere","ggplot2",
         "gstat","ks","leaflet","lwgeom",
         "maptools","mapview","raster",
         "rasterVis","rgdal","rgeos","rnaturalearth", 
         "rnaturalearthdata", "sf", "sp","spatstat",
         "tidyverse")


#installs packages for any packages not in the installed packages on my R
if(any(!(pkgs %in% installed.packages()))){
  install.packages(pkgs[!(pkgs %in% installed.packages())],
                   dependencies = TRUE)}

libraries(pkgs)

```

summary of task:
* put NA as hash marks
* reference: https://mhallwor.github.io/_pages/Tidyverse_intro

```{r}
setwd("D:\\CCPR\\01-18-22")
#data <- readxl::read_xlsx("DQ_Groupings.xlsx")
data <- readxl::read_xlsx("Figure 4.xlsx")
```

Notes:

suggestion: manual search with the viewer with shortened root (tokenization, scrub out punctuation, spaces)
make note if still cannot find in world dataset



```{r}
# devtools::install_github("ropensci/rnaturalearthhires")
library("rnaturalearth")
library("rnaturalearthdata")
library("rnaturalearthhires")

world <- ne_countries(scale = "large", returnclass = "sf")
class(world)

francepoly <- st_cast(world$geometry[world$name_long=="France"], "POLYGON")
# 1: french guiana
# 4,6,7,19,20: guadaloupe
# 3: martinique
# 9,10: mayotte
#8: reunion
chilepoly <- st_cast(world$geometry[world$name_long=="Chile"], "MULTIPOLYGON")
chileunion <- chilepoly %>% st_sf() %>% mutate(area = st_area(.)) %>% summarise(area = sum(area))

world2 <- ne_countries(scale = "small", returnclass = "sf")
#world3 <- ne_countries(scale = "medium", returnclass = "sf")
chile2 <- st_cast(world2$geometry[world2$name_long=="Chile"], "MULTIPOLYGON")
#chile3 <- st_cast(world3$geometry[world3$name_long=="Chile"], "MULTIPOLYGON")
world$geometry[world$name_long=="Chile"] <- world2$geometry[world2$name_long=="Chile"]

fgupoly <- st_cast(francepoly[1], "MULTIPOLYGON")
glppoly <- st_union(st_cast(francepoly[c(4,6,7,19,20)], "MULTIPOLYGON"))
mtqpoly <- st_cast(francepoly[3], "MULTIPOLYGON")
mytpoly <- st_union(st_cast(francepoly[c(9,10)], "MULTIPOLYGON"))
reupoly <- st_cast(francepoly[8], "MULTIPOLYGON")
frpoly <-st_union(st_cast(francepoly[c(2,5,11,12,13,14,15,16,17,18)], "MULTIPOLYGON"))

```

```{r}
# if country name not in world data set then list name 

mismatched <- vector()

# change all names to lowercase
for (i in 1:nrow(data)){
  if (data$worldsf[i] %in% c(world$name, world$name_long, world$formal_en)){ 
    next
  }
  else{ # append to vector if name in data does not match exactly to names in world 
    x <- data$worldsf[i]
    mismatched <- append(mismatched, x)
  }
}

# write code to sort these names
```


```{r}

world$Categories <- "NA"

fdepts <- c("French Guiana", "Guadaloupe", "Martinique", "Mayotte", "Reunion")
# manual add of polygons for the missing french departments

poly <- francepoly[1]
fguianadata <- c(rep("French Guiana", 3), "2", poly) # 2
guadaloupedata <- as.data.table(c(rep("Guadaloupe", 3), "2", poly)) # 2
martiniquedata <- as.data.table(c(rep("Martinique", 3), "2", poly)) # 2
mayottedata <- as.data.table(c(rep("Mayotte", 3), "2", poly)) # 2
reuniondata <- as.data.table(c(rep("Reunion", 3), "1", poly)) # 1



l <- list(fguianadata,guadaloupedata,martiniquedata,mayottedata,reuniondata)
t <- rbindlist(l, use.names=TRUE, fill=TRUE)
colnames(t) <- c("name","name_long","formal_en", "Categories", "geometry")
t$geometry <- c(fgupoly, glppoly, mtqpoly, mytpoly, reupoly)
t <- st_as_sf(t)

x <- "not updated"
for (i in 1:length(data$worldsf)){
  if (data$worldsf[i] %in% c(world$name, world$name_long, world$formal_en)){
    x <- grep(data$worldsf[i], world$name)
    if (length(x) == 0){
      x <- grep(data$worldsf[i], world$name_long)
    }
    if (length(x) == 0){
      x <- grep(data$worldsf[i], world$formal_en)
    }
    world$Categories[x] <- data$Categories[i]
  }
  else{
    next
  }
}

world$Categories <- factor(world$Categories, levels = c("NA", "1", "2", "3"))



testdata <- world[, c("name","name_long","formal_en","Categories", "geometry")]

testdata <- rbind(testdata, t)
testdata$geometry[testdata$name_long=="France"] <- frpoly

testdata$pattern[testdata$Categories == "NA"] <- "Yes"
testdata$pattern[testdata$Categories != "NA"] <- "No"

```

```{r}
knitr::opts_chunk$set(dev = "ragg_png")
# remotes::install_github("coolbutuseless/ggpattern")
library(ggpattern)
options(ggpattern_use_R4.1_features = FALSE)

labels <- c("NA", "Maximum < 2 years", 
            "Maximum > 2 years, average < 2 years", 
            "Average > 2 years")

# blue color plot
bluepalette <- c("NA" = "gray80", "1" = "#bdd7e7", "2" = "#6baed6", "3" = "#2171b5")
blues <- ggplot() +
  geom_sf(data = testdata, aes(fill = Categories), size = 0.05)+
  scale_fill_manual(name = "Annual Decline, 2019-2021",
                    values=bluepalette, labels  = str_wrap(labels,33)) +
  theme_classic()

blues2 <- ggplot() +
  geom_sf(data = testdata, aes(fill = Categories), size=0.05, colour = "gray95")+
  scale_fill_manual(name = "Annual Decline, 2019-2021",
                    values=bluepalette, labels  = str_wrap(labels,33)) +
  theme_classic()

altbluepalette <- c("NA" = "white", "1" = "#bdd7e7", "2" = "#6baed6", "3" = "#2171b5")
blues3 <- ggplot() +
  geom_sf(data = testdata, aes(fill = Categories), size=0.05)+
  scale_fill_manual(name = "Annual Decline, 2019-2021",
                    values=altbluepalette, labels  = str_wrap(labels,33)) +
  theme_classic()

# gray color palettes
graypalette <-c("NA" = "white", "1" = "gray80", "2" = "gray50", "3" = "gray30")
graycolourpalette <-c("NA" = "gray90", "1" = "gray80", "2" = "gray50", "3" = "gray30")


# initial gray dot
graydots <- ggplot(data = testdata, aes(fill = Categories, pattern = Categories)) +
  geom_sf_pattern(pattern_colour = "black", 
                  pattern_fill = "black",
                  pattern_angle = 45,
                  pattern_density = 0.1,
                  pattern_spacing = 0.025,
                  pattern_linetype = 1,
                  pattern_size = 0.15,
                  pattern_key_scale_factor = 0.8) +
  scale_fill_manual(name = "Annual Decline, 2019-2021",
                    values=graypalette, labels = str_wrap(labels,33)) +
  scale_pattern_manual(name = "Annual Decline, 2019-2021",
                       values=c("NA" = "circle", 
                                "1" = "none", 
                                "2" = "none", 
                                "3" = "none"),
                       labels  = str_wrap(labels,33)) +
  theme_classic()

graydots2 <- ggplot(data = testdata, aes(fill = Categories, pattern = Categories)) +
  geom_sf_pattern(pattern_colour = "black", 
                  pattern_fill = "black",
                  pattern_angle = 45,
                  pattern_density = 0.1,
                  pattern_spacing = 0.020,
                  pattern_linetype = 1,
                  pattern_size = 0.15,
                  pattern_key_scale_factor = 0.9) +
  scale_fill_manual(name = "Annual Decline, 2019-2021",
                    values=graypalette, labels = str_wrap(labels,33)) +
  scale_pattern_manual(name = "Annual Decline, 2019-2021",
                       values=c("NA" = "circle", 
                                "1" = "none", 
                                "2" = "none", 
                                "3" = "none"),
                       labels  = str_wrap(labels,33)) +
  theme_classic()

#light borders
grayborders <- ggplot(data = testdata, 
                    aes(fill = Categories, pattern = Categories)) +
  geom_sf_pattern(pattern_colour = "black", 
                  pattern_fill = "black",
                  pattern_angle = 45,
                  pattern_density = 0.1,
                  pattern_spacing = 0.025,
                  pattern_linetype = 1,
                  pattern_size = 0.15,
                  pattern_key_scale_factor = 0.8,
                  size = 0.05,
                  colour = "grey90") +
  scale_fill_manual(name = "Annual Decline, 2019-2021",
                    values=graypalette, labels = str_wrap(labels,33)) +
  scale_pattern_manual(name = "Annual Decline, 2019-2021",
                       values=c("NA" = "circle", 
                                "1" = "none", 
                                "2" = "none", 
                                "3" = "none"),
                       labels  = str_wrap(labels,33)) +
  theme_classic()

grayborders2 <- ggplot(data = testdata, 
                    aes(fill = Categories, pattern = Categories)) +
  geom_sf_pattern(pattern_colour = "black", 
                  pattern_fill = "black",
                  pattern_angle = 45,
                  pattern_density = 0.1,
                  pattern_spacing = 0.025,
                  pattern_linetype = 1,
                  pattern_size = 0.1,
                  pattern_key_scale_factor = 0.8,
                  size = 0.1,
                  colour = "grey90") +
  scale_fill_manual(name = "Annual Decline, 2019-2021",
                    values=graypalette, labels = str_wrap(labels,33)) +
  scale_pattern_manual(name = "Annual Decline, 2019-2021",
                       values=c("NA" = "circle", 
                                "1" = "none", 
                                "2" = "none", 
                                "3" = "none"),
                       labels  = str_wrap(labels,33)) +
  theme_classic()

grayborders3 <- ggplot(data = testdata, 
                    aes(fill = Categories, pattern = Categories)) +
  geom_sf_pattern(pattern_colour = "black", 
                  pattern_fill = "black",
                  pattern_angle = 45,
                  pattern_density = 0.1,
                  pattern_spacing = 0.020,
                  pattern_linetype = 1,
                  pattern_size = 0.15,
                  pattern_key_scale_factor = .9,
                  size = 0.1,
                  colour = "grey90") +
  scale_fill_manual(name = "Annual Decline, 2019-2021",
                    values=graypalette, labels = str_wrap(labels,33)) +
  scale_pattern_manual(name = "Annual Decline, 2019-2021",
                       values=c("NA" = "circle", 
                                "1" = "none", 
                                "2" = "none", 
                                "3" = "none"),
                       labels  = str_wrap(labels,33)) +
  theme_classic()

#no borders besides NA
grayminimal <- ggplot(data = testdata, 
                    aes(fill = Categories, pattern = Categories, colour = Categories), 
                    size = 0.001) +
  geom_sf_pattern(pattern_colour = "black", 
                  pattern_fill = "black",
                  pattern_angle = 45,
                  pattern_density = 0.1,
                  pattern_spacing = 0.025,
                  pattern_linetype = 1,
                  pattern_size = 0.15,
                  pattern_key_scale_factor = 0.8) +
  scale_fill_manual(name = "Annual Decline, 2019-2021",
                    values=graypalette, labels = str_wrap(labels,33)) +
  scale_colour_manual(name = "Annual Decline, 2019-2021",
                      values=graycolourpalette, labels = str_wrap(labels,33)) +
  scale_pattern_manual(name = "Annual Decline, 2019-2021",
                       values=c("NA" = "circle", 
                                "1" = "none", 
                                "2" = "none", 
                                "3" = "none"),
                       labels  = str_wrap(labels,33)) +
  theme_classic()
```


```{r}
setwd("D:\\CCPR\\02-23-22")

pdf("blues.pdf")
print(blues)
dev.off()

pdf("blues2.pdf")
print(blues2)
dev.off()

pdf("blues3.pdf")
print(blues3)
dev.off()

pdf("graydots.pdf")
print(graydots)
dev.off()

pdf("graydots2.pdf")
print(graydots2)
dev.off()

pdf("grayborders.pdf")
print(grayborders)
dev.off()

pdf("grayborders2.pdf")
print(grayborders2)
dev.off()

pdf("grayborders3.pdf")
print(grayborders3)
dev.off()

pdf("grayminimal.pdf")
print(grayminimal)
dev.off()
```


```{r}
```

